### ISSUE TITLE
Consistent use of team_name parameter

### ISSUE THREAD

**Issue by markberridge** [ministryofjustice/cloud-platform-terraform-dynamodb-cluster#6]
I have been sharing a terraform variable `team_name` across this dynamodb module and the rds terraform module (github.com/ministryofjustice/cloud-platform-terraform-rds-instance).  For the rds module the `team_name` parameter is fed into a tag but for the dynamodb module it is used to create the iam user.  As well as being confusing, with the validation rules being different it caused an error when initially provisioning dynamodb.

Is it possible to make the modules consistent?

**Comment by jakemulley** [comment]
Closing this, as the module no longer uses `team_name` (or `owner`) to provision an IAM user.
